import MaleyLean.Papers.BivalenceNonDegenerateReasoning
import MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction
import MaleyLean.Papers.NonDegenerateConstructionAndKernelOfAdmissibility
import MaleyLean.Papers.Poincare
